sudo: false
language: python

os:
    - linux

# build matrix - test on different emacs versions
env:
  matrix:
    - EVM_EMACS=emacs-26.1-travis

matrix:
  include:
    - env: EVM_EMACS=emacs-24.4-travis
    - env: EVM_EMACS=emacs-24.5-travis
    - env: EVM_EMACS=emacs-25.1-travis
    - env: EVM_EMACS=emacs-25.2-travis
    - env: EVM_EMACS=emacs-25.3-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip

script:
  - emacs -Q --batch -L .
    --load literate-elisp
    --eval "(setf literate-elisp-test-p t)"
    --funcall literate-elisp-batch-load literate-elisp.org
    --funcall literate-elisp-batch-load readme.org
    --funcall ert-run-tests-batch-and-exit

