language: generic

os:
    - linux

# build matrix - test on different emacs versions
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

install:

  # linux
  - if [[ "$TRAVIS_OS_NAME-$EMACS" == "linux-emacs24" ]]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [[ "$TRAVIS_OS_NAME-$EMACS" == "linux-emacs-snapshot" ]]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get -qq -f install &&
        sudo apt-get install -qq emacs-snapshot;
    fi

script:
  - emacs -Q --batch -L .
    --load literate-elisp
    --eval "(setf literate-elisp-test-p t)"
    --funcall literate-batch-load literate-elisp.org
    --funcall literate-batch-load readme.org
    --funcall ert-run-tests-batch-and-exit

